export const data = [
  {
    id: 642138,
    title: "Easy Vegetable Fried Rice",
    image: "https://img.spoonacular.com/recipes/642138-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 2,
    missedIngredientCount: 8,
    missedIngredients: [
      {
        id: 1001,
        amount: 1,
        unit: "tbsp",
        unitLong: "tablespoon",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        meta: [],
        image:
          "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 11124,
        amount: 0.33333334,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Produce",
        name: "carrots",
        original: "1/3 cup thinly sliced carrots",
        originalName: "thinly sliced carrots",
        meta: ["thinly sliced"],
        image:
          "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 1123,
        amount: 1,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "egg",
        original: "1 egg",
        originalName: "egg",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 11215,
        amount: 1,
        unit: "clove",
        unitLong: "clove",
        unitShort: "clove",
        aisle: "Produce",
        name: "garlic",
        original: "1 clove garlic, minced",
        originalName: "garlic, minced",
        meta: ["minced"],
        image: "https://img.spoonacular.com/ingredients_100x100/garlic.png",
      },
      {
        id: 11216,
        amount: 1,
        unit: "tbsp",
        unitLong: "tablespoon",
        unitShort: "Tbsp",
        aisle: "Produce",
        name: "ginger",
        original: "1 tbsp minced ginger",
        originalName: "minced ginger",
        meta: ["minced"],
        image: "https://img.spoonacular.com/ingredients_100x100/ginger.png",
      },
      {
        id: 11052,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Produce",
        name: "green beans",
        original: "½ cup green beans",
        originalName: "green beans",
        meta: [],
        image:
          "https://img.spoonacular.com/ingredients_100x100/green-beans-or-string-beans.jpg",
      },
      {
        id: 11304,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Produce",
        name: "peas",
        original: "½ cup peas",
        originalName: "peas",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/peas.jpg",
      },
      {
        id: 16124,
        amount: 4,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Ethnic Foods",
        name: "soy sauce",
        original: "soy sauce to taste",
        originalName: "soy sauce to taste",
        meta: ["to taste"],
        image: "https://img.spoonacular.com/ingredients_100x100/soy-sauce.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 11090,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Produce",
        name: "broccoli",
        original: "1 cup broccoli",
        originalName: "broccoli",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/broccoli.jpg",
      },
      {
        id: 10220445,
        amount: 2,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Pasta and Rice",
        name: "rice",
        original: "2 cups cooked rice",
        originalName: "cooked rice",
        meta: ["cooked"],
        extendedName: "cooked rice",
        image:
          "https://img.spoonacular.com/ingredients_100x100/uncooked-white-rice.png",
      },
    ],
    unusedIngredients: [
      {
        id: 5006,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Meat",
        name: "whole chicken",
        original: "chicken",
        originalName: "chicken",
        meta: [],
        image:
          "https://img.spoonacular.com/ingredients_100x100/whole-chicken.jpg",
      },
    ],
    likes: 13,
  },
];
